uses:
  - django
  - celery

pylint:
  disable:
    - django-not-configured
    - import-outside-toplevel
    - unused-import

pyflakes:
  disable:
    - F401

pycodestyle:
  max-line-length: 200  # увеличиваем допустимую длину строки, если нужно

ignore-paths:
  - venv

ignore-patterns:
  - .*migrations
